sonar.projectKey=checkrr_react
sonar.qualitygate.wait=true
sonar.sources=.
sonar.exclusions=**/*test.tsx,**/*spec.tsx,**/*.test.tsx,**/*.spec.tsx, **/*.stories.tsx,**/pages/*,Main.tsx,webpack.*.js,webpack.*.js,**/*spec.ts,**/*.spec.ts,coverage/**,**/lcov-report/**,**/*.html,**/*test.ts,**/*test.tsx,**/*stories.tsx,**/*stories.ts,**/__mocks__/**,**/setupTests.ts,**/eslint.config.js,**/jest.config.js,**/services/**,**/utils/**